export const questionBank = [
  {
    id: 'q001',
    year: 2023,
    month: 'May',
    language: 'Chinese A',
    category: '语言与文学',
    textType: '小说',
    theme: '身份认同',
    question: '比较鲁迅《故乡》与张爱玲《倾城之恋》中主人公身份认同的变化，分析作者如何通过细节描写呈现这种变化。',
    texts: ['鲁迅《故乡》', '张爱玲《倾城之恋》'],
    luXunText: '《呐喊·故乡》',
    zhangAiLingText: '《倾城之恋·倾城之恋》',
    analysis: '本题要求对比分析两篇小说中主人公身份认同的变化，需要从人物形象、情节发展、环境描写等维度进行分析。',
    outlineType: '文本对比分析',
    difficulty: 'high',
    tags: ['身份认同', '故乡', '倾城之恋', '对比分析']
  },
  {
    id: 'q002',
    year: 2023,
    month: 'Nov',
    language: 'Chinese A',
    category: '文学',
    textType: '小说',
    theme: '文化冲突',
    question: '分析鲁迅《阿Q正传》与张爱玲《金锁记》中文化冲突的表现形式，比较作者如何通过叙事视角传达文化张力。',
    texts: ['鲁迅《阿Q正传》', '张爱玲《金锁记》'],
    luXunText: '《呐喊·阿Q正传》',
    zhangAiLingText: '《倾城之恋·金锁记》',
    analysis: '本题聚焦文化冲突，需要关注叙事的讽刺效果、人物的悲剧性以及作者对社会的批判。',
    outlineType: '文本对比分析',
    difficulty: 'high',
    tags: ['文化冲突', '阿Q正传', '金锁记', '叙事视角']
  },
  {
    id: 'q003',
    year: 2022,
    month: 'May',
    language: 'Chinese A',
    category: '语言与文学',
    textType: '小说',
    theme: '权力与压迫',
    question: '比较鲁迅《孔乙己》与张爱玲《连环套》中底层人物被压迫的命运，分析作者如何通过叙事策略呈现社会不公。',
    texts: ['鲁迅《孔乙己》', '张爱玲《连环套》'],
    luXunText: '《呐喊·孔乙己》',
    zhangAiLingText: '《倾城之恋·连环套》',
    analysis: '本题要求分析底层人物的悲剧命运，需要关注叙事视角、人物塑造以及社会批判的呈现方式。',
    outlineType: '文本对比分析',
    difficulty: 'medium',
    tags: ['权力与压迫', '孔乙己', '连环套', '底层人物']
  },
  {
    id: 'q004',
    year: 2022,
    month: 'Nov',
    language: 'Chinese A',
    category: '语言与文学',
    textType: '小说',
    theme: '爱与失落',
    question: '分析鲁迅《伤逝》与张爱玲《炉火》中爱情与失落的主题，比较作者如何通过情感表达呈现人物的内心世界。',
    texts: ['鲁迅《伤逝》', '张爱玲《炉火》'],
    luXunText: '《彷徨·伤逝》',
    zhangAiLingText: '《倾城之恋·炉火》',
    analysis: '本题考察散文中的情感表达，需要分析作者如何通过叙事技巧、意象选择和语言节奏传达复杂的情感。',
    outlineType: '文本对比分析',
    difficulty: 'medium',
    tags: ['爱与失落', '伤逝', '炉火', '情感表达']
  },
  {
    id: 'q005',
    year: 2021,
    month: 'May',
    language: 'Chinese A',
    category: '语言与文学',
    textType: '小说',
    theme: '自由与束缚',
    question: '比较鲁迅《在酒楼上》与张爱玲《创世纪》中人物对自由的追求与束缚，分析作者如何通过环境描写呈现人物的内心困境。',
    texts: ['鲁迅《在酒楼上》', '张爱玲《创世纪》'],
    luXunText: '《彷徨·在酒楼上》',
    zhangAiLingText: '《倾城之恋·创世纪》',
    analysis: '本题聚焦自由与束缚的对立，需要分析叙事视角的选择如何影响读者对人物处境的理解。',
    outlineType: '文本对比分析',
    difficulty: 'high',
    tags: ['自由与束缚', '在酒楼上', '创世纪', '环境描写']
  },
  {
    id: 'q006',
    year: 2021,
    month: 'Nov',
    language: 'Chinese A',
    category: '文学',
    textType: '小说',
    theme: '身份认同',
    question: '分析鲁迅《祝福》与张爱玲《怨女》中女性身份的建构与瓦解，比较作者如何通过人物命运呈现性别困境。',
    texts: ['鲁迅《祝福》', '张爱玲《怨女》'],
    luXunText: '《彷徨·祝福》',
    zhangAiLingText: '《倾城之恋·怨女》',
    analysis: '本题关注女性身份问题，需要分析人物如何被社会期待所束缚，以及身份认同如何被摧毁。',
    outlineType: '文本对比分析',
    difficulty: 'high',
    tags: ['身份认同', '祝福', '怨女', '女性命运']
  },
  {
    id: 'q007',
    year: 2020,
    month: 'May',
    language: 'Chinese A',
    category: '语言与文学',
    textType: '小说',
    theme: '社会批判',
    question: '比较鲁迅《药》与张爱玲《金锁记》中对社会病态的批判，分析作者如何通过象征手法深化批判效果。',
    texts: ['鲁迅《药》', '张爱玲《金锁记》'],
    luXunText: '《呐喊·药》',
    zhangAiLingText: '《倾城之恋·金锁记》',
    analysis: '本题要求分析象征手法在社会批判中的作用，需要关注意象的选择与主题的关联。',
    outlineType: '文本对比分析',
    difficulty: 'medium',
    tags: ['社会批判', '药', '金锁记', '象征手法']
  },
  {
    id: 'q008',
    year: 2020,
    month: 'Nov',
    language: 'Chinese A',
    category: '语言与文学',
    textType: '小说',
    theme: '传统与现代',
    question: '分析鲁迅《风波》与张爱玲《倾城之恋》中传统与现代的文化冲突，比较作者如何通过人物对话呈现文化张力。',
    texts: ['鲁迅《风波》', '张爱玲《倾城之恋》'],
    luXunText: '《呐喊·风波》',
    zhangAiLingText: '《倾城之恋·倾城之恋》',
    analysis: '本题聚焦文化冲突，需要关注人物如何代表不同的文化立场，以及对话如何揭示文化冲突。',
    outlineType: '文本对比分析',
    difficulty: 'medium',
    tags: ['传统与现代', '风波', '倾城之恋', '文化冲突']
  },
  {
    id: 'q009',
    year: 2019,
    month: 'May',
    language: 'Chinese A',
    category: '文学',
    textType: '小说',
    theme: '孤独与隔阂',
    question: '比较鲁迅《狂人日记》与张爱玲《多少恨》中人物的孤独感，分析作者如何通过叙事视角呈现人与人之间的隔阂。',
    texts: ['鲁迅《狂人日记》', '张爱玲《多少恨》'],
    luXunText: '《呐喊·狂人日记》',
    zhangAiLingText: '《倾城之恋·多少恨》',
    analysis: '本题考察孤独与隔阂的主题，需要分析叙事视角的选择如何影响读者对人物孤独感的理解。',
    outlineType: '文本对比分析',
    difficulty: 'high',
    tags: ['孤独与隔阂', '狂人日记', '多少恨', '叙事视角']
  },
  {
    id: 'q010',
    year: 2019,
    month: 'Nov',
    language: 'Chinese A',
    category: '语言与文学',
    textType: '小说',
    theme: '身份认同',
    question: '分析鲁迅《阿Q正传》与张爱玲《连环套》中人物自我欺骗的机制，比较作者如何通过讽刺手法呈现人性的弱点。',
    texts: ['鲁迅《阿Q正传》', '张爱玲《连环套》'],
    luXunText: '《呐喊·阿Q正传》',
    zhangAiLingText: '《倾城之恋·连环套》',
    analysis: '本题聚焦自我欺骗与精神胜利法，需要分析讽刺手法如何揭示人性的复杂。',
    outlineType: '文本对比分析',
    difficulty: 'high',
    tags: ['身份认同', '阿Q正传', '连环套', '讽刺手法']
  },
  {
    id: 'q011',
    year: 2018,
    month: 'May',
    language: 'Chinese A',
    category: '语言与文学',
    textType: '小说',
    theme: '爱与失落',
    question: '比较鲁迅《伤逝》与张爱玲《倾城之恋》中爱情与物质的关系，分析作者如何通过情节设计呈现爱情的不确定性。',
    texts: ['鲁迅《伤逝》', '张爱玲《倾城之恋》'],
    luXunText: '《彷徨·伤逝》',
    zhangAiLingText: '《倾城之恋·倾城之恋》',
    analysis: '本题考察爱情与现实的关系，需要关注人物选择背后的社会因素和心理动机。',
    outlineType: '文本对比分析',
    difficulty: 'medium',
    tags: ['爱与失落', '伤逝', '倾城之恋', '爱情与物质']
  },
  {
    id: 'q012',
    year: 2018,
    month: 'Nov',
    language: 'Chinese A',
    category: '文学',
    textType: '小说',
    theme: '权力与压迫',
    question: '分析鲁迅《孔乙己》与张爱玲《金锁记》中权力对人物的压制，比较作者如何通过环境描写强化压迫感。',
    texts: ['鲁迅《孔乙己》', '张爱玲《金锁记》'],
    luXunText: '《呐喊·孔乙己》',
    zhangAiLingText: '《倾城之恋·金锁记》',
    analysis: '本题聚焦权力压制，需要分析社会制度、家庭关系如何压迫人物，以及人物的无力感。',
    outlineType: '文本对比分析',
    difficulty: 'medium',
    tags: ['权力与压迫', '孔乙己', '金锁记', '环境描写']
  },
  {
    id: 'q013',
    year: 2017,
    month: 'May',
    language: 'Chinese A',
    category: '语言与文学',
    textType: '小说',
    theme: '社会批判',
    question: '比较鲁迅《故乡》与张爱玲《创世纪》中城乡差距的呈现，分析作者如何通过人物命运揭示社会问题。',
    texts: ['鲁迅《故乡》', '张爱玲《创世纪》'],
    luXunText: '《呐喊·故乡》',
    zhangAiLingText: '《倾城之恋·创世纪》',
    analysis: '本题要求分析城乡差距与社会问题，需要关注人物如何在社会变革中失去立足之地。',
    outlineType: '文本对比分析',
    difficulty: 'medium',
    tags: ['社会批判', '故乡', '创世纪', '城乡差距']
  },
  {
    id: 'q014',
    year: 2017,
    month: 'Nov',
    language: 'Chinese A',
    category: '语言与文学',
    textType: '小说',
    theme: '文化冲突',
    question: '分析鲁迅《狂人日记》与张爱玲《炉火》中传统文化的压抑性，比较作者如何通过象征手法批判文化糟粕。',
    texts: ['鲁迅《狂人日记》', '张爱玲《炉火》'],
    luXunText: '《呐喊·狂人日记》',
    zhangAiLingText: '《倾城之恋·炉火》',
    analysis: '本题聚焦传统文化的压抑性，需要分析象征手法如何揭示文化的黑暗面。',
    outlineType: '文本对比分析',
    difficulty: 'high',
    tags: ['文化冲突', '狂人日记', '炉火', '象征手法']
  },
  {
    id: 'q015',
    year: 2016,
    month: 'May',
    language: 'Chinese A',
    category: '文学',
    textType: '小说',
    theme: '身份认同',
    question: '比较鲁迅《在酒楼上》与张爱玲《多少恨》中知识分子的困境，分析作者如何通过人物形象呈现时代的焦虑。',
    texts: ['鲁迅《在酒楼上》', '张爱玲《多少恨》'],
    luXunText: '《彷徨·在酒楼上》',
    zhangAiLingText: '《倾城之恋·多少恨》',
    analysis: '本题聚焦知识分子的精神困境，需要分析人物如何在新旧时代交替中迷失自我。',
    outlineType: '文本对比分析',
    difficulty: 'high',
    tags: ['身份认同', '在酒楼上', '多少恨', '知识分子']
  },
  {
    id: 'q016',
    year: 2016,
    month: 'Nov',
    language: 'Chinese A',
    category: '语言与文学',
    textType: '小说',
    theme: '爱与失落',
    question: '分析鲁迅《伤逝》与张爱玲《连环套》中女性的依附与失落，比较作者如何通过情感叙事呈现女性的悲剧命运。',
    texts: ['鲁迅《伤逝》', '张爱玲《连环套》'],
    luXunText: '《彷徨·伤逝》',
    zhangAiLingText: '《倾城之恋·连环套》',
    analysis: '本题考察女性的依附与失落，需要分析人物如何在情感中失去自我。',
    outlineType: '文本对比分析',
    difficulty: 'medium',
    tags: ['爱与失落', '伤逝', '连环套', '女性命运']
  },
  {
    id: 'q017',
    year: 2015,
    month: 'May',
    language: 'Chinese A',
    category: '语言与文学',
    textType: '小说',
    theme: '传统与现代',
    question: '比较鲁迅《风波》与张爱玲《怨女》中婚姻与家族的压力，分析作者如何通过人物关系呈现传统制度的束缚。',
    texts: ['鲁迅《风波》', '张爱玲《怨女》'],
    luXunText: '《呐喊·风波》',
    zhangAiLingText: '《倾城之恋·怨女》',
    analysis: '本题聚焦婚姻与家族制度，需要分析人物如何被传统制度所束缚和压迫。',
    outlineType: '文本对比分析',
    difficulty: 'medium',
    tags: ['传统与现代', '风波', '怨女', '婚姻制度']
  },
  {
    id: 'q018',
    year: 2015,
    month: 'Nov',
    language: 'Chinese A',
    category: '文学',
    textType: '小说',
    theme: '社会批判',
    question: '分析鲁迅《药》与张爱玲《金锁记》中"物化"主题的呈现，比较作者如何通过人物命运批判社会的拜物现象。',
    texts: ['鲁迅《药》', '张爱玲《金锁记》'],
    luXunText: '《呐喊·药》',
    zhangAiLingText: '《倾城之恋·金锁记》',
    analysis: '本题聚焦"物化"主题，需要分析人物如何被物质或象征物所定义和束缚。',
    outlineType: '文本对比分析',
    difficulty: 'high',
    tags: ['社会批判', '药', '金锁记', '物化主题']
  },
  {
    id: 'q019',
    year: 2014,
    month: 'May',
    language: 'Chinese A',
    category: '语言与文学',
    textType: '小说',
    theme: '孤独与隔阂',
    question: '比较鲁迅《故乡》与张爱玲《倾城之恋》中人与人之间的疏离，分析作者如何通过叙事呈现现代人的孤独感。',
    texts: ['鲁迅《故乡》', '张爱玲《倾城之恋》'],
    luXunText: '《呐喊·故乡》',
    zhangAiLingText: '《倾城之恋·倾城之恋》',
    analysis: '本题考察人与人之间的疏离，需要分析叙事如何呈现人际关系的脆弱和孤独。',
    outlineType: '文本对比分析',
    difficulty: 'medium',
    tags: ['孤独与隔阂', '故乡', '倾城之恋', '人际疏离']
  },
  {
    id: 'q020',
    year: 2014,
    month: 'Nov',
    language: 'Chinese A',
    category: '语言与文学',
    textType: '小说',
    theme: '权力与压迫',
    question: '分析鲁迅《阿Q正传》与张爱玲《创世纪》中家族的统治与反抗，比较作者如何通过家族叙事呈现权力的运作。',
    texts: ['鲁迅《阿Q正传》', '张爱玲《创世纪》'],
    luXunText: '《呐喊·阿Q正传》',
    zhangAiLingText: '《倾城之恋·创世纪》',
    analysis: '本题聚焦家族中的权力运作，需要分析家长制如何压迫个人，以及人物的反抗。',
    outlineType: '文本对比分析',
    difficulty: 'high',
    tags: ['权力与压迫', '阿Q正传', '创世纪', '家族叙事']
  },
  {
    id: 'q021',
    year: 2013,
    month: 'May',
    language: 'Chinese A',
    category: '文学',
    textType: '小说',
    theme: '文化冲突',
    question: '比较鲁迅《孔乙己》与张爱玲《炉火》中知识分子的悲剧性，分析作者如何通过人物形象批判社会的冷漠。',
    texts: ['鲁迅《孔乙己》', '张爱玲《炉火》'],
    luXunText: '《呐喊·孔乙己》',
    zhangAiLingText: '《倾城之恋·炉火》',
    analysis: '本题聚焦知识分子的悲剧，需要分析人物如何被社会所抛弃和遗忘。',
    outlineType: '文本对比分析',
    difficulty: 'medium',
    tags: ['文化冲突', '孔乙己', '炉火', '知识分子']
  },
  {
    id: 'q022',
    year: 2013,
    month: 'Nov',
    language: 'Chinese A',
    category: '语言与文学',
    textType: '小说',
    theme: '身份认同',
    question: '分析鲁迅《狂人日记》与张爱玲《多少恨》中"疯子"与"正常人"的边界，比较作者如何通过叙事挑战社会规范。',
    texts: ['鲁迅《狂人日记》', '张爱玲《多少恨》'],
    luXunText: '《呐喊·狂人日记》',
    zhangAiLingText: '《倾城之恋·多少恨》',
    analysis: '本题聚焦正常与异常的边界，需要分析叙事如何挑战既定的社会规范和价值观念。',
    outlineType: '文本对比分析',
    difficulty: 'high',
    tags: ['身份认同', '狂人日记', '多少恨', '社会规范']
  },
  {
    id: 'q023',
    year: 2012,
    month: 'May',
    language: 'Chinese A',
    category: '语言与文学',
    textType: '小说',
    theme: '自由与束缚',
    question: '比较鲁迅《在酒楼上》与张爱玲《怨女》中人物的精神困境，分析作者如何通过象征手法呈现自由的遥不可及。',
    texts: ['鲁迅《在酒楼上》', '张爱玲《怨女》'],
    luXunText: '《彷徨·在酒楼上》',
    zhangAiLingText: '《倾城之恋·怨女》',
    analysis: '本题聚焦精神困境，需要分析象征手法如何呈现人物对自由的渴望与无力实现。',
    outlineType: '文本对比分析',
    difficulty: 'high',
    tags: ['自由与束缚', '在酒楼上', '怨女', '精神困境']
  },
  {
    id: 'q024',
    year: 2012,
    month: 'Nov',
    language: 'Chinese A',
    category: '文学',
    textType: '小说',
    theme: '社会批判',
    question: '分析鲁迅《故乡》与张爱玲《连环套》中"看与被看"的关系，比较作者如何通过叙事呈现社会的窥视文化。',
    texts: ['鲁迅《故乡》', '张爱玲《连环套》'],
    luXunText: '《呐喊·故乡》',
    zhangAiLingText: '《倾城之恋·连环套》',
    analysis: '本题聚焦"看与被看"的关系，需要分析叙事如何揭示社会的窥视和评判机制。',
    outlineType: '文本对比分析',
    difficulty: 'medium',
    tags: ['社会批判', '故乡', '连环套', '窥视文化']
  },
  {
    id: 'q025',
    year: 2011,
    month: 'May',
    language: 'Chinese A',
    category: '语言与文学',
    textType: '小说',
    theme: '传统与现代',
    question: '比较鲁迅《风波》与张爱玲《倾城之恋》中旧式人物在新时代的挣扎，分析作者如何通过幽默与讽刺呈现文化的转型。',
    texts: ['鲁迅《风波》', '张爱玲《倾城之恋》'],
    luXunText: '《呐喊·风波》',
    zhangAiLingText: '《倾城之恋·倾城之恋》',
    analysis: '本题聚焦旧式人物在新时代的挣扎，需要分析幽默与讽刺如何服务于文化批判。',
    outlineType: '文本对比分析',
    difficulty: 'medium',
    tags: ['传统与现代', '风波', '倾城之恋', '文化转型']
  }
]

export const sampleEssays = []

export const luXunStories = [
  { id: 'luxun-01', title: '狂人日记', collection: '呐喊', description: '中国现代文学史上第一篇白话小说，通过"狂人"的视角揭示封建礼教的吃人本质。' },
  { id: 'luxun-02', title: '孔乙己', collection: '呐喊', description: '通过酒店小伙计的视角，刻画了一个科举制度牺牲者的悲剧形象。' },
  { id: 'luxun-03', title: '药', collection: '呐喊', description: '以人血馒头为线索，揭示了群众的愚昧和革命者的悲哀。' },
  { id: 'luxun-04', title: '明天', collection: '呐喊', description: '单四嫂子丧子的故事，展现了底层妇女的悲惨命运。' },
  { id: 'luxun-05', title: '一件小事', collection: '呐喊', description: '通过车夫撞到老妇人后主动承担责任的故事，歌颂普通人的高尚品格。' },
  { id: 'luxun-06', title: '头发的故事', collection: '呐喊', description: '通过N先生对头发问题的议论，批判了辛亥革命的不彻底性。' },
  { id: 'luxun-07', title: '风波', collection: '呐喊', description: '以辫子问题为焦点，展现了辛亥革命后农村社会的真实面貌。' },
  { id: 'luxun-08', title: '故乡', collection: '呐喊', description: '"我"回乡卖屋的经历，刻画了农民闰土的悲惨变化。' },
  { id: 'luxun-09', title: '阿Q正传', collection: '呐喊', description: '通过阿Q的精神胜利法，批判了国民的劣根性。' },
  { id: 'luxun-10', title: '端午节', collection: '呐喊', description: '通过方玄绰的经历，展现了知识分子的灰色人生。' },
  { id: 'luxun-11', title: '白光', collection: '呐喊', description: '陈士成落榜后疯狂寻找祖先遗产的故事，揭示了科举制度对人心的毒害。' },
  { id: 'luxun-12', title: '兔和猫', collection: '呐喊', description: '通过孩子对兔和猫的态度，表达了对弱小者的同情。' },
  { id: 'luxun-13', title: '社戏', collection: '呐喊', description: '回忆童年看社戏的美好经历，与现实形成鲜明对比。' },
  { id: 'luxun-14', title: '祝福', collection: '彷徨', description: '祥林嫂的悲剧命运，揭示了封建礼教对妇女的压迫。' },
  { id: 'luxun-15', title: '在酒楼上', collection: '彷徨', description: '吕纬甫的故事，展现了知识分子在革命后的精神颓唐。' },
  { id: 'luxun-16', title: '伤逝', collection: '彷徨', description: '涓生与子君的爱情悲剧，揭示了个性解放的局限性。' }
]

export const zhangAiLingStories = [
  { id: 'zhang-01', title: '倾城之恋', collection: '倾城之恋', description: '白流苏与范柳原的爱情博弈，探讨爱情与物质、生存的关系。' },
  { id: 'zhang-02', title: '金锁记', collection: '倾城之恋', description: '曹七巧的悲剧人生，展现了金钱如何异化人心。' },
  { id: 'zhang-03', title: '连环套', collection: '倾城之恋', description: '霓喜与多个男人的情感纠葛，揭示女性在经济社会中的依附地位。' },
  { id: 'zhang-04', title: '创世纪', collection: '倾城之恋', description: '潆珠与家族压抑的抗争，揭示旧式家族的毁灭性影响。' },
  { id: 'zhang-05', title: '多少恨', collection: '倾城之恋', description: '现代都市中的爱情悲剧，展现情感的错位与失落。' },
  { id: 'zhang-06', title: '炉火', collection: '倾城之恋', description: '对民国往事的回忆，探讨情感与理智的冲突。' },
  { id: 'zhang-07', title: '怨女', collection: '倾城之恋', description: '银娣的悲剧命运，深入刻画旧式女性的内心世界。' }
]
